### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by edunham** [OSFeels/language#7]
This repo is public, and the conference is all about open source, but code needs more than just public distribution to make it legally open. Could you add a LICENSE file so that others know how they're allowed to share and modify the contents of this repo?

http://choosealicense.com/ might be helpful here.

Thanks!

**Comment by ootoovak** [comment]
Yes, please. I like what I have read of the CoC and Enforcement Policy so I wouldn't mind proposing a modified version of it for the space I work in. So if it does happen to be open source the type of licence would be good to know. 👍🏽

**Comment by strand** [comment]
Thanks! Fixed.

**Comment by edunham** [comment]
Thank you!

**Comment by ootoovak** [comment]
Awesome, thanks!
